MERGE INTO MPA (ID, NAME) VALUES (1, 'G');
MERGE INTO MPA (ID, NAME) VALUES (2, 'PG');
MERGE INTO MPA (ID, NAME) VALUES (3, 'PG-13');
MERGE INTO MPA (ID, NAME) VALUES (4, 'R');
MERGE INTO MPA (ID, NAME) VALUES (5, 'NC-17');

MERGE INTO GENRE (ID, NAME) VALUES (1, 'Комедия');
MERGE INTO GENRE (ID, NAME) VALUES (2, 'Драма');
MERGE INTO GENRE (ID, NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRE (ID, NAME) VALUES (4, 'Триллер');
MERGE INTO GENRE (ID, NAME) VALUES (5, 'Документальный');
MERGE INTO GENRE (ID, NAME) VALUES (6, 'Боевик');
